"""Contrato de armazenamento de objetos privado, sem dependência de fornecedor."""

from __future__ import annotations

from typing import Any, Protocol


class StorageService(Protocol):
    def upload(self, *, key: str, content: bytes, content_type: str) -> dict[str, Any]: ...
    def create_presigned_upload_url(self, *, key: str, content_type: str, expires_in: int) -> str: ...
    def create_presigned_download_url(self, *, key: str, expires_in: int) -> str: ...
    def exists(self, *, key: str) -> bool: ...
    def delete(self, *, key: str) -> None: ...
    def get_metadata(self, *, key: str) -> dict[str, Any]: ...
